// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXqSWLL3tGkgey-S4hysodACKn5kVJAiw',
    appId: '1:312821844850:web:b50f4f5d0456d83e376beb',
    messagingSenderId: '312821844850',
    projectId: 'smart-gloves-4e9ae',
    authDomain: 'smart-gloves-4e9ae.firebaseapp.com',
    storageBucket: 'smart-gloves-4e9ae.firebasestorage.app',
    measurementId: 'G-8R48TWN9RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdCi5251ZkLYAIUdMdKubSsigK-dBkhXE',
    appId: '1:312821844850:android:bd9e636281cf51cb376beb',
    messagingSenderId: '312821844850',
    projectId: 'smart-gloves-4e9ae',
    storageBucket: 'smart-gloves-4e9ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAlG1eeerxxd1RbOlulg5BU75JtJB43zE',
    appId: '1:312821844850:ios:39aea2be55c55b81376beb',
    messagingSenderId: '312821844850',
    projectId: 'smart-gloves-4e9ae',
    storageBucket: 'smart-gloves-4e9ae.firebasestorage.app',
    iosBundleId: 'com.example.smartGlove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAlG1eeerxxd1RbOlulg5BU75JtJB43zE',
    appId: '1:312821844850:ios:39aea2be55c55b81376beb',
    messagingSenderId: '312821844850',
    projectId: 'smart-gloves-4e9ae',
    storageBucket: 'smart-gloves-4e9ae.firebasestorage.app',
    iosBundleId: 'com.example.smartGlove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXqSWLL3tGkgey-S4hysodACKn5kVJAiw',
    appId: '1:312821844850:web:67c1eab05d8fc944376beb',
    messagingSenderId: '312821844850',
    projectId: 'smart-gloves-4e9ae',
    authDomain: 'smart-gloves-4e9ae.firebaseapp.com',
    storageBucket: 'smart-gloves-4e9ae.firebasestorage.app',
    measurementId: 'G-4LK766Z0SF',
  );
}
